fix numpy 2.0 int32 scalars to_bytes() error   - in NumPy 2.0, int32 scalars to_bytes() fails with 'AttributeError: 'numpy.int32' object has no attribute 'to_bytes''   - this is because of stricter handling of types in Numpy 2.0 than NumPy 1.x   - cast numpy.int32 to a native Python int before calling to_bytes()